### ISSUE TITLE
Part ImageNet Seg Labels

### ISSUE THREAD

**Issue by joshmyersdean** [TACJu/PartImageNet#12]
Hello again!

What is the meaning of each pixel label in the segmentation labels? They do not appear to match up with the 39 part labels and 10 whole labels. The json files also only contain the height and width of the image.

```python
classes =[]
for i in tqdm(range(len(dataset_train))):
    image, whole_mask, part_mask = dataset_train[i]
    classes += np.unique(whole_mask).tolist()

c = Counter(classes)
print(c) # has counts for labels from 0 to 158
```

Could you please provide clarification?

**Comment by joshmyersdean** [comment]
Parts and whole labels also appear to share the same pixel values (e.g., see below).

![image](https://github.com/TACJu/PartImageNet/assets/42389546/29d9c71f-d79b-4c92-937e-fe4b639d597d)

**Comment by TACJu** [comment]
Sorry for the confusion. The definition of 'whole' in both the PartImageNet and Compositor is the individual class instead of the super-class (e.g., different car classes are labeled with different numbers in whole annotation). As a result, there are 158 classes from ImageNet in PartImageNet and after treating 158 as the label for background, the pixel value ranges from 0-158. The json file is only for my personal data reading usage. You can directly read the labeled png file to get all the information.

The part gt file follows similar logic. 40 parts in total and 40 is used for background so the pixel value ranges from 0-40.

**Comment by joshmyersdean** [comment]
Ah that makes sense. So when computing mIoU you compute over 157 classes (ignore index for background) for wholes and 39 for parts?

**Comment by TACJu** [comment]
We compute the background mIoU in both part and whole setting. As a result, our reported numbers are averaged with all classes mIoU (including background).

**Comment by joshmyersdean** [comment]
Gotcha, thank you!

**Comment by joshmyersdean** [comment]
Sorry one last question @TACJu, do you provide a mapping of category id to name?

**Comment by TACJu** [comment]
Could you elaborate more on what you mean by `category id to name'? (e.g. part gt id -> part name, object gt id -> object name?)

**Comment by joshmyersdean** [comment]
Yes. So 0 -> "NAME 1", 1 -> "NAME 2", etc.
